### PR TITLE
Implementation of Consent Manager 2.0 + fixes after reviews

### LINKED ISSUE #89: Improve Code Quality of the Study Manager Endpoint
We will raise the overall code quality of the Study Manager endpoint through a structured, multi-step process. The goal is a cleaner architecture, clearer responsibilities, and a stable contract between backend and frontend:

## 1. Gather UI Requirements
- **Goal:** Understand exactly what the UI needs from the backend.
- **Tasks:**
  - [ ] #90 
  - [ ] #91 
  - [ ] #92 
  - [ ] #93 

## 2. Implement Backend Improvements
- **Goal:** Refactor or implement backend logic based on the architecture plan.
- **Tasks:**
  - [ ] #95 

## 3. Adjust Frontend if Contract Changes
- **Goal:** Align the frontend with any refined backend behavior.
- **Tasks:**
  - [ ] Update frontend API calls and data models if endpoint details changed
    - Refer to #91 and #92
  - [ ] Verify the UI flows against the new backend behavior (manual testing)

### PR DESCRIPTION
**Pull request by simhue**

### CODE REVIEW

File: admin-gui/src/main/webapp/semantic/src/site/globals/site.variables
Comment (akomii) [inline admin-gui/src/main/webapp/semantic/src/site/globals/site.variables:1]: Duplicate with #73  ?

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/PatientEntriesRequestDTO.java [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+public class PatientEntriesRequestDTO {
+	public Participation opt;
+	public String comment;
+	// should sic be automatically generated or manually inserted
+	public boolean generateSic;
+
+	// lists of sics and extensions, each element of one list corresponds to the element in the other list at the same index
+	// if a sic is going to be generated, the value of the respective index should be null
+	public List<String> sics;
+	public List<String> extensions;
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/PatientEntriesRequestDTO.java]: Why are you using here parallel lists? This is very fragile. What was the reason not to use a map?

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 2]
```diff
@@ -1,218 +1,492 @@
...
+    @POST
+    @Consumes({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
+    public Response createEntry(@PathParam("studyId") String id, @PathParam("reference") PatientReference ref, @PathParam("root") String root,
+                                @PathParam("extension") String ext, PatientEntryRequestDTO entry) throws IOException {
+        Study study = this.getStudy(id);
+
+        PatientEntry pat = study.getPatientByID(ref, root, ext);
+        if (pat != null) {
+            log.log(Level.WARNING, "Cannot create entry, PatientEntry already exists.");
+            return Response.status(Status.CONFLICT).entity("Patient*in existiert bereits").build();
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Do not sent human-readable error messages. These are endpoints. A machine interacts with them (frontend). The translation to human-readable should be done in Frontend to UI

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 3]
```diff
@@ -1,218 +1,492 @@
...
+        }
+
+        pat = study.getPatientBySIC(entry.sic);
+        if (pat != null) {
+            log.log(Level.WARNING, "Cannot create entry, SIC already exists.");
+            return Response.status(Status.CONFLICT).entity("Studien-ID existiert bereits").build();
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: See above

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 4]
```diff
@@ -1,218 +1,492 @@
...
+    @PUT
+    @Consumes({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
+    public Response updateEntry(@PathParam("studyId") String id, @PathParam("reference") PatientReference ref, @PathParam("root") String root,
+                                @PathParam("extension") String ext, PatientEntryRequestDTO entry) throws IOException {
+        val study = this.getStudy(id);
+
+        PatientEntry oldEntry = study.getPatientByID(ref, root, ext);
+        if (oldEntry == null) {
+            log.log(Level.WARNING, "Cannot update entry, entry does not exist");
+            return Response.status(Status.BAD_REQUEST).entity("Patient*in nicht gefunden").build();
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Here too

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 5]
```diff
@@ -1,218 +1,492 @@
...
+     */
+    @Secured
+    @Path("{studyId}/{reference}/{root}{p:/?}{extension:.*}")
+    @DELETE
+    public Response deleteEntry(@PathParam("studyId") String id, @PathParam("reference") PatientReference ref, @PathParam("root") String root,
+                                @PathParam("extension") String ext) throws IOException {
+        Study study = this.getStudy(id);
+        PatientEntry pat = study.getPatientByID(ref, root, ext);
+        if (pat == null) {
+            return Response.status(Status.BAD_REQUEST).entity("Patient*in nicht gefunden").build();
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Here too

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 6]
```diff
@@ -1,218 +1,492 @@
...
+    @GET
+    @Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
+    public PatientEntry getEntry(@PathParam("studyId") String id, @PathParam("reference") PatientReference ref, @PathParam("root") String root,
+                                 @PathParam("extension") String ext) throws IOException {
+        Study study = this.getStudy(id);
+        return study.getPatientByID(ref, root, ext);
+    }
+
+    /**
+     * Gets an entry by the specified study id, reference type, root and extension parameters.
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Not what the method does

File: admin-gui/src/main/java/org/aktin/dwh/admin/JavaTimeMapperProvider.java
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/JavaTimeMapperProvider.java:1]: Probably not necessary (fixed by downgrading WildFly)

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 7]
```diff
@@ -1,218 +1,492 @@
...
+     * @param id: study id
+     * @param sic unique student object identifier
+     * @return PatientEntry that belongs to the given parameters
+     * @throws IOException
+     */
+    @Path("{studyId}/{sic}")
+    @GET
+    @Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
+    public PatientEntry getEntryBySic(@PathParam("studyId") String id, @PathParam("sic") String sic) throws IOException {
+        Study study = this.getStudy(id);
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: What if study is null?

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 2 above)
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Instead of Response you could also return:

throw new ClientErrorException(Status.CONFLICT);

This is a preformatted machine-readable status message

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 8]
```diff
@@ -1,218 +1,492 @@
...
+                                @PathParam("extension") String ext, PatientEntryRequestDTO entry) throws IOException {
+        val study = this.getStudy(id);
+
+        PatientEntry oldEntry = study.getPatientByID(ref, root, ext);
+        if (oldEntry == null) {
+            log.log(Level.WARNING, "Cannot update entry, entry does not exist");
+            return Response.status(Status.BAD_REQUEST).entity("Patient*in nicht gefunden").build();
+        }
+        PatientEntry newEntry = study.getPatientByID(ref, root, ext);
+        newEntry.setComment(entry.comment);
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Modifying an object should be done in the service, not the endpoint. The endpoint only receives commands which are forwarded to the service. Only for next time. Keep it as is now

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 9]
```diff
@@ -1,218 +1,492 @@
...
+    public Response updateEntry(@PathParam("studyId") String id, @PathParam("reference") PatientReference ref, @PathParam("root") String root,
+                                @PathParam("extension") String ext, PatientEntryRequestDTO entry) throws IOException {
+        val study = this.getStudy(id);
+
+        PatientEntry oldEntry = study.getPatientByID(ref, root, ext);
+        if (oldEntry == null) {
+            log.log(Level.WARNING, "Cannot update entry, entry does not exist");
+            return Response.status(Status.BAD_REQUEST).entity("Patient*in nicht gefunden").build();
+        }
+        PatientEntry newEntry = study.getPatientByID(ref, root, ext);
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: What?? So newEntry = oldEntry? Why not just

newEntry = oldEntry.copy()

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 10]
```diff
@@ -1,218 +1,492 @@
...
+        newEntry.setComment(entry.comment);
+
+        newEntry = study.updatePatient(oldEntry, newEntry);
+
+        return Response.created(buildEntryLocation(newEntry)).entity(newEntry).build();
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: You return ok(), not created(). You did not create a new Entry....

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 5 above)
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Why even BAD_REQUEST?? Why not NOT_FOUND?

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 11]
```diff
@@ -1,218 +1,492 @@
...
+     */
+    @Secured
+    @Path("entries/{studyId}/{reference}/{root}")
+    @PUT
+    @Consumes({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
+    public ArrayList<PatientEntriesResponseDTO> validateEntries(@PathParam("studyId") String id,
+                                                                @PathParam("reference") PatientReference ref,
+                                                                @PathParam("root") String root,
+                                                                PatientEntriesRequestDTO entries) throws IOException {
+        Study study = this.getStudy(id);
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: What if study not found?

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/PatientEntriesResponseDTO.java [hunk 12]
```diff
@@ -0,0 +1,15 @@
+package org.aktin.dwh.admin.optin;
+
+import lombok.Getter;
+import lombok.Setter;
+import org.aktin.dwh.optinout.PatientEncounter;
+import org.aktin.dwh.optinout.PatientMasterData;
+
+@Getter @Setter
+public class PatientEntriesResponseDTO {
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/PatientEntriesResponseDTO.java]: Shouldnt this be called [...]Entry[...]DTO instead of Entries?

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 13]
```diff
@@ -1,218 +1,492 @@
...
+    private SecurityContext security;
+
+    /**
+     * Gets all patient entries of all existing studies.
+     *
+     * @return list of all patient entries of all studies
+     * @throws IOException
+     */
+    @GET
+    public List<PatientEntry> getEntries() throws IOException {
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Is this method even necessary? For what?

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 14]
```diff
@@ -1,218 +1,492 @@
...
+    }
+
+    /**
+     * Get all patient entries that belong to the study of the specified id.
+     *
+     * @param id
+     * @return Response with status 'ok' and the list of entries
+     * @throws IOException
+     */
+    @Path("{studyId}")
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Better studies/{studyId}. Also for all other Paths

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 15]
```diff
@@ -1,218 +1,492 @@
...
+
+        pat = study.getPatientBySIC(entry.sic);
+        if (pat != null) {
+            log.log(Level.WARNING, "Cannot create entry, SIC already exists.");
+            return Response.status(Status.CONFLICT).entity("Studien-ID existiert bereits").build();
+        }
+
+        if (study.getSicGeneration() == SICGeneration.AutoAndManual && (entry.sic == null || entry.sic.isEmpty())) {
+            entry.sic = study.generateSIC();
+        }
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Such logic belongs in the service, not the endpoint

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 16]
```diff
@@ -1,218 +1,492 @@
...
+        val validatedEntries = new ArrayList<PatientEntriesResponseDTO>();
+
+        for (int i = 0; i < entries.extensions.size(); i++) {
+            val extension = entries.extensions.get(i);
+            val foundEntry = new PatientEntriesResponseDTO();
+            foundEntry.setExtension(extension);
+            validatedEntries.add(foundEntry);
+
+            if (!entries.generateSic) {
+                val sic = entries.sics.get(i);
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: What happens in case of an index drift?

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 17]
```diff
@@ -1,218 +1,492 @@
...
+     *                   This object is updated with validation status if validation fails.
+     * @param sic     The SIC (Study Instance Code) to be validated.
+     * @return {@code true} if the SIC is found to be a duplicate or already exists in the study;
+     *         {@code false} otherwise.
+     * @throws IOException If an I/O error occurs during the validation process.
+     */
+    private boolean validateSic(PatientEntriesRequestDTO entries, Study study, PatientEntriesResponseDTO foundEntry, String sic) throws IOException {
+        if (sic != null) {
+            if (entries.sics.stream().filter(s -> Objects.equals(s, sic)).count() > 1) {
+                foundEntry.setEntryValidation(EntryValidation.DUPLICATE_SIC);
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Is this processed in the later steps somehow?

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 18]
```diff
@@ -1,218 +1,492 @@
...
+    @Path("entries/{studyId}/{reference}/{root}")
+    @POST
+    @Consumes({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
+    public Response createEntries(@PathParam("studyId") String id, @PathParam("reference") PatientReference ref, @PathParam("root") String root,
+                                  PatientEntriesRequestDTO entries) throws IOException {
+        Study study = this.getStudy(id);
+
+        for (int i = 0; i < entries.extensions.size(); i++) {
+            val extension = entries.extensions.get(i);
+            val sic = entries.sics.get(i);
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Again, the possibility of an index drift

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 19]
```diff
@@ -1,218 +1,492 @@
...
+     */
+    private boolean checkEncountersAndMasterData(PatientReference ref, String root, PatientEntriesResponseDTO foundEntry, String extension) throws IOException {
+        val encounters = sm.loadEncounters(ref, root, extension);
+
+        if (encounters.isEmpty()) {
+            foundEntry.setEntryValidation(EntryValidation.ENCOUNTERS_NOT_FOUND);
+            return true;
+        }
+
+        encounters.sort(Comparator.comparing(PatientEncounter::getStartDate));
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Sort ascending and take first meaning the oldest entry?

**Review by akomii — COMMENTED** [review]
Review WIP. Only Java code done so far. Project not buildable via mvn:

```
[ERROR] ▲ [WARNING] The glob pattern import("./**/*.entry.js*") did not match any files [empty-glob]
[ERROR] 
[ERROR]     node_modules/@stencil/core/internal/client/index.js:169:2:
[ERROR]       169 │   `./${bundleId}.entry.js${BUILD5.hotModuleReplacement && hmrVers...
[ERROR]           ╵   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR] 
[ERROR] 
[ERROR] ✘ [ERROR] Could not resolve "semantic/dist/semantic.min.css"
[ERROR] 
[ERROR]     angular:styles/global:styles:2:8:
[ERROR]       2 │ @import 'semantic/dist/semantic.min.css';
[ERROR]         ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR] 
[ERROR]   You can mark the path "semantic/dist/semantic.min.css" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
[ERROR] 
[ERROR] 
[ERROR] ✘ [ERROR] Could not resolve "semantic/dist/semantic.js" [plugin angular-script-global]
[ERROR] 
[ERROR] 
```

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 20]
```diff
@@ -1,218 +1,492 @@
...
+     * @param id
+     * @return Response with status 'ok' and the list of entries
+     * @throws IOException
+     */
+    @Path("{studyId}")
+    @GET
+    public Response getEntriesByStudy(@PathParam("studyId") String id) throws IOException {
+        Study s = this.getStudy(id);
+        List<PatientEntry> list = new ArrayList<>();
+        list.addAll(s.allPatients());
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: s.allPatients() already returns List<? extends PatientEntry>

In getStudies() you do a cast, but here you are filling up a new list?

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 21]
```diff
@@ -1,218 +1,492 @@
...
+     * @return PatientEntry that belongs to the given parameters
+     * @throws IOException
+     */
+    @Path("{studyId}/{reference}/{root}{p:/?}{extension:.*}")
+    @GET
+    @Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
+    public PatientEntry getEntry(@PathParam("studyId") String id, @PathParam("reference") PatientReference ref, @PathParam("root") String root,
+                                 @PathParam("extension") String ext) throws IOException {
+        Study study = this.getStudy(id);
+        return study.getPatientByID(ref, root, ext);
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: This logic should be in the service. 

So you are calling in StudyManagerImpl an SQL Query to get all Studies
Then you loop to these studies to get a specific study
Then you loop through the found study to get a specific patient

Why not just add the method to StudyManager and implement a SQL Query that does this?

**Comment by simhue** [comment]
> Review WIP. Only Java code done so far. Project not buildable via mvn:
> 
> ```
> [ERROR] ▲ [WARNING] The glob pattern import("./**/*.entry.js*") did not match any files [empty-glob]
> [ERROR] 
> [ERROR]     node_modules/@stencil/core/internal/client/index.js:169:2:
> [ERROR]       169 │   `./${bundleId}.entry.js${BUILD5.hotModuleReplacement && hmrVers...
> [ERROR]           ╵   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> [ERROR] 
> [ERROR] 
> [ERROR] ✘ [ERROR] Could not resolve "semantic/dist/semantic.min.css"
> [ERROR] 
> [ERROR]     angular:styles/global:styles:2:8:
> [ERROR]       2 │ @import 'semantic/dist/semantic.min.css';
> [ERROR]         ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> [ERROR] 
> [ERROR]   You can mark the path "semantic/dist/semantic.min.css" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
> [ERROR] 
> [ERROR] 
> [ERROR] ✘ [ERROR] Could not resolve "semantic/dist/semantic.js" [plugin angular-script-global]
> [ERROR] 
> [ERROR] 
> ```

During a merge a line got deleted by accident. I pushed a fix.

File: admin-gui/src/main/webapp/semantic/src/site/globals/site.variables
Comment (simhue) [reply admin-gui/src/main/webapp/semantic/src/site/globals/site.variables:1]: You are right, I merged #73 branch into this one with commit 4ae3473

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 17 above)
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Yes, in the frontend

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 11 above)
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: getStudy throws a NotFoundException

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 13 above)
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: it is definitely not used in the frontend, going to remove it

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 20 above)
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Not my original code, will change to a cast nevertheless

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 7 above)
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: getStudy throws a NotFound exception, resulting in a 404

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/PatientEntriesResponseDTO.java (hunk 12 above)
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/PatientEntriesResponseDTO.java]: I named it like that because it was the response for PatientEntriesRequestDTO, but you are right

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 21 above)
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Because then I do not need to touch two additional packages (dwh-api and dwh-query) and the computational impact should be negligible - correct me if I'm wrong

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 9 above)
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: because then I have to write a new function that creates a deep copy of oldEntry, which gets used only once (so far), it means more code to maintain and touching additional pacakges, by calling getPatientById twice, I still get a separate object with "just" a single read operation on the database.

File: admin-gui/src/main/java/org/aktin/dwh/admin/JavaTimeMapperProvider.java
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/JavaTimeMapperProvider.java:1]: I needed this to properly seriallize Instant datatypes

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 14 above)
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: I'd rather wait with these changes until I am continuing with the tests, I am going to write a test case where the front end calls each endpoint, that would make any route changes easier to check

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 22]
```diff
@@ -1,218 +1,461 @@
...
+     *
+     * @param id: study id
+     * @param sic unique student object identifier
+     * @return PatientEntry that belongs to the given parameters
+     * @throws IOException
+     */
+    @Path("{studyId}/{sic}")
+    @GET
+    @Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
+    public PatientEntry getEntryBySic(@PathParam("studyId") String id, @PathParam("sic") String sic) throws IOException {
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Endpoints should never throw an Exception... Where would it go?

File: admin-gui/pom.xml [hunk 23]
```diff
@@ -251,7 +263,16 @@
                 <artifactId>maven-war-plugin</artifactId>
                 <version>3.1.0</version>
                 <configuration>
-                    <warSourceExcludes>node_modules/**,**/*.ts,**/*.js.map,.idea/**,.vscode/**</warSourceExcludes>
+                    <warSourceExcludes>node_modules/**,.angular/**,*.json,*.md,.browserslistrc,.vscode/**,.idea/**,dist/**,public/**,src/**</warSourceExcludes>
```
Comment (rwm) [inline admin-gui/pom.xml:266]: das soll ja den sourcecode enthalten und nur die kompilierten Teile auslassen. Warum steht hier public/ und src/ als ausnahmen drin?

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 24]
```diff
@@ -1,218 +1,461 @@
...
+
+        PatientEntry pat = study.getPatientByID(ref, root, ext);
+        if (pat != null) {
+            throw OptInError.buildError(Status.CONFLICT, OptInErrorType.PATIENT_ALREADY_EXISTS, "Cannot create entry, PatientEntry already exists");
+        }
+
+        pat = study.getPatientBySIC(entry.sic);
+        if (pat != null) {
+            throw OptInError.buildError(Status.CONFLICT, OptInErrorType.SIC_ALREADY_EXISTS, "Cannot create entry, SIC {0} already exists", entry.sic);
+        }
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Again, an Endpoint is machine readable. Instead of creating a new Pojo to differentiate existing patient and sics you should use:

```java
throw new ClientErrorException(Status.CONFLICT);
```

Alternatively:
```java
throw new ClientErrorException(
    Response.status(Status.CONFLICT)
        .type(MediaType.APPLICATION_JSON)
        .entity("{detail: OptInErrorType.SIC_ALREADY_EXISTS}")
        .build());
```

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 25]
```diff
@@ -1,218 +1,461 @@
...
+     * @param ref:  type of the patient reference
+     * @param root: root number
+     * @param ext:  extension number, can be empty
+     * @return PatientEntry that belongs to the given parameters
+     * @throws IOException
+     */
+    @Path("{studyId}/{reference}/{root}{p:/?}{extension:.*}")
+    @GET
+    @Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
+    public Response getEntry(@PathParam("studyId") String id, @PathParam("reference") PatientReference ref, @PathParam("root") String root,
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Endpoints should never throw an IOException... Where would it go?

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 26]
```diff
@@ -1,218 +1,461 @@
...
+                                 @PathParam("extension") String ext) throws IOException {
+        Study study = this.getStudy(id);
+        return Response.ok(study.getPatientByID(ref, root, ext)).build();
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: If study not found, 200 is returned with an empty body

it should be a 404

File: admin-gui/src/main/webapp/.gitignore [hunk 27]
```diff
@@ -5,3 +5,4 @@ npm-debug.log
 debug.log
 *.js
 *.js.map
+semantic
```
Comment (rwm) [inline admin-gui/src/main/webapp/.gitignore:8]: Hier fehlen kommentare was semantic ist und warum das ausgenommen wird.

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/ValidationErrorType.java [hunk 28]
```diff
@@ -0,0 +1,22 @@
...
+    SIC_MISSING, // No SIC given, when it is required
+
+    // Database Response???
+    ENTRY_FOUND, // Patient entry already exists
+    SIC_FOUND, // SIC already exists
+    MASTER_DATA_NOT_FOUND, // No master data in db found
+    ENCOUNTERS_NOT_FOUND, // No encounters in db found
+
+    // Processing States
+    VALID,
```
Comment (rwm) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/ValidationErrorType.java]: was für ein Fehler ist VALID???

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 29]
```diff
@@ -1,218 +1,461 @@
...
+    @Context
+    private SecurityContext security;
+
+    /**
+     * Gets a list of all studies.
+     *
+     * @return list of studies
+     * @throws IOException
+     */
+    @Path("studies")
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Better to just remove the Path annoation for consistency

GET optin/studies -> all studies
GET optin/2 -> all entries of study with id 2??

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 30]
```diff
@@ -1,218 +1,461 @@
...
+    @Path("{studyId}/{reference}/{root}{p:/?}{extension:.*}")
+    @PUT
+    @Consumes({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
+    public Response updateEntry(@PathParam("studyId") String id, @PathParam("reference") PatientReference ref, @PathParam("root") String root,
+                                @PathParam("extension") String ext, PatientEntryRequestDTO entry) throws IOException {
+        val study = this.getStudy(id);
+
+        PatientEntry oldEntry = study.getPatientByID(ref, root, ext);
+        if (oldEntry == null) {
+            throw OptInError.buildError(Status.NOT_FOUND, OptInErrorType.PATIENT_NOT_FOUND, "Patient not found");
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Why do you need OptInError for this? Why not just:

```java
throw new ClientErrorException(Status.NOT_FOUND);
```

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/EntryDTO.java [hunk 31]
```diff
@@ -0,0 +1,13 @@
...
+
+import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
+
+import javax.xml.bind.annotation.XmlAccessType;
+import javax.xml.bind.annotation.XmlAccessorType;
+
+@XmlAccessorType(XmlAccessType.FIELD)
+@JsonIgnoreProperties(ignoreUnknown = true)
+public class EntryDTO {
+	public String extension;
```
Comment (rwm) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/EntryDTO.java]: Javadoc fehlt komplett. Was ist "extension"? Variablenname schlecht gewählt.

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 9 above)
Comment (akomii) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: I still dont get it... It a PUT, its called `updateEntry`, but all it does it update the comment?

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 32]
```diff
@@ -1,218 +1,461 @@
...
+    @DELETE
+    public Response deleteEntry(@PathParam("studyId") String id, @PathParam("reference") PatientReference ref, @PathParam("root") String root,
+                                @PathParam("extension") String ext) throws IOException {
+        Study study = this.getStudy(id);
+        PatientEntry pat = study.getPatientByID(ref, root, ext);
+        if (pat == null) {
+            throw OptInError.buildError(Status.NOT_FOUND, OptInErrorType.PATIENT_NOT_FOUND, "Patient not found");
+        }
+        pat.delete(security.getUserPrincipal().getName());
+        return Response.ok().build();
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Commonly, NO_CONTENT / 204 is returned if an DELETE is successful

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 29 above)
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: or change the "optin" to "studies" because optin/2 -> what is an optin with the id 2?

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 25 above)
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Not my original code, we should adress that when the code base gets redesigned eventually

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 26 above)
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: getStudy throws a not found exception when empty, but not getPatientByID, I'm going to add it

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 22 above)
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: see comment above

**Comment by akomii** [comment]
DWH is buildable, but not accessible:

image

**Comment by akomii** [comment]
`/optin` path is missing in `OptInEndpoint` and does not work:

image

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 33]
```diff
@@ -70,40 +100,23 @@ public Response getEntriesByStudy(@PathParam("studyId") String id) throws IOExce
...
      * @param id:   study id
      * @param ref:  type of the patient reference
-     * @param root: root number
      * @param ext:  extension number, can be empty
      * @return PatientEntry that belongs to the given parameters
-     * @throws IOException
      */
-    @Path("{studyId}/{reference}/{root}{p:/?}{extension:.*}")
+    @Path("{studyId}/patients/{reference}/{extension}")
     @GET
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:100]: Image

Is this an error? The reference seems correct if I compare it with the business logic...

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 34]
```diff
@@ -41,27 +56,42 @@ public class OptInEndpoint {
...
      */
-    @Path("{studyId}")
+    @Path("{id}/patients")
     @GET
-    public Response getEntriesByStudy(@PathParam("studyId") String id) throws IOException {
-        Study s = this.getStudy(id);
-
-        return Response.ok(s.allPatients()).build();
+    @Produces(MediaType.APPLICATION_JSON)
+    public Response getPatientsOfStudy(@PathParam("id") String id) {
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:80]: Image

The response should be in a self-describing machine-readable structure. See JSON RFC 7807 for an example

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 35]
```diff
@@ -41,27 +56,42 @@ public class OptInEndpoint {
...
+        List<PatientEntry> patients = null;
+        try {
+            patients = patientService.getAllPatientsOfStudy(id);
+        } catch (IOException e) {
+            throw new RuntimeException(e);
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Where does the RuntimeExecption go? The endpoint should be the final interface between business logic and outer world. Everything, that happens in the logic should be returned somehow as a response to the outer world.

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 36]
```diff
@@ -112,326 +125,168 @@ public Response getEntryBySic(@PathParam("studyId") String id, @PathParam("sic")
...
-     * @param ext  extension
+     * @param extensions  extension
      * @return list of patient encounters
-     * @throws IOException
      */
-    @Path("encounter/{reference}/{root}{p:/?}{extension:.*}")
-    @GET
-    @Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
+    @Path("patients/{reference}/encounters")
+    @POST
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:124]: Why is this a POST? The method seems to be a getter

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 37]
```diff
@@ -112,326 +125,168 @@ public Response getEntryBySic(@PathParam("studyId") String id, @PathParam("sic")
...
-     * @param root root id
-     * @param ext  extension
+     * @param extensions  extension
      * @return list of patient encounters
-     * @throws IOException
      */
-    @Path("encounter/{reference}/{root}{p:/?}{extension:.*}")
-    @GET
-    @Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
+    @Path("patients/{reference}/encounters")
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: `/studies/patients/` reads a bit weird as an URI. Wouldnt it make sense to split it up into an `studies` endpoint and an `patients` endpoint?

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 38]
```diff
@@ -112,326 +125,168 @@ public Response getEntryBySic(@PathParam("studyId") String id, @PathParam("sic")
...
-     * @param root:  root number
      * @param ext:   extension number, can be empty
      * @param entry: object that contains further information (participation, sic, comment) about the entry
      * @return Response with status 'created' if the entry was successfully created, otherwise Response with status 'conflict' if the entry already exists
-     * @throws IOException
      */
-    @Secured
-    @Path("{studyId}/{reference}/{root}{p:/?}{extension:.*}")
+    @Path("{studyId}/patients/{reference}/{extension}")
     @PUT
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: A PUT should be idempotent replacement. Here we have create-or-update logic with existence checks, meaning POST and PATCH behaviour

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 39]
```diff
@@ -41,27 +56,42 @@ public class OptInEndpoint {
...
+    @Produces(MediaType.APPLICATION_JSON)
+    public Response getStudies() {
+        List<? extends Study> studies = null;
+        try {
+            studies = studyService.getStudies();
+        } catch (IOException e) {
+            throw ErrorUtils.buildError(Status.NOT_FOUND, OptInErrorType.UNKNOWN, "An error occurred while retrieving studies:");
+        }
+        if(studies == null || studies.isEmpty()) {
+            throw ErrorUtils.buildError(Status.NOT_FOUND, OptInErrorType.STUDIES_NOT_FOUND, "No studies found");
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: An empty collection is still a valid response, so it must return 200 either way

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 40]
```diff
@@ -70,40 +100,23 @@ public Response getEntriesByStudy(@PathParam("studyId") String id) throws IOExce
...
-     */
-    @Path("{studyId}/{sic}")
-    @GET
-    @Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
-    public Response getEntryBySic(@PathParam("studyId") String id, @PathParam("sic") String sic) throws IOException {
-        Study study = this.getStudy(id);
-        PatientEntry patientEntry = study.getPatientBySIC(sic);
         if(patientEntry == null) {
-            throw OptInError.buildError(Status.NOT_FOUND, OptInErrorType.PATIENT_NOT_FOUND, "Patient not found");
+            throw ErrorUtils.buildError(Status.NOT_FOUND, OptInErrorType.PATIENT_NOT_FOUND, "Patient not found");
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: This 404 is correct, because the patient resource may be absent

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 41]
```diff
@@ -112,326 +125,168 @@ public Response getEntryBySic(@PathParam("studyId") String id, @PathParam("sic")
...
-        return Response.ok(sm.loadMasterData(ref, root, ext)).build();
+                                  List<String> extensions) {
+        List<PatientEncounter> encounters = null;
+        try {
+            encounters = patientService.getEncounters(ref, extensions);
+        } catch (IOException e) {
+            throw new RuntimeException(e);
+        }
+        if(encounters == null || encounters.isEmpty()) {
+            throw ErrorUtils.buildError(Status.NOT_FOUND, OptInErrorType.ENCOUNTERS_NOT_FOUND, "Encounters not found");
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Again, an empty collection is still a valid resposne

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 42]
```diff
@@ -112,326 +125,168 @@ public Response getEntryBySic(@PathParam("studyId") String id, @PathParam("sic")
...
+    @Path("{studyId}/patients/{reference}/{extension}")
     @DELETE
-    public Response deleteEntry(@PathParam("studyId") String id, @PathParam("reference") PatientReference ref, @PathParam("root") String root,
-                                @PathParam("extension") String ext) throws IOException {
-        Study study = this.getStudy(id);
-        PatientEntry pat = study.getPatientByID(ref, root, ext);
-        if (pat == null) {
-            throw OptInError.buildError(Status.NOT_FOUND, OptInErrorType.PATIENT_NOT_FOUND, "Patient not found");
+    public Response deleteEntry(@PathParam("studyId") String id, @PathParam("reference") PatientReference ref,
+                                @PathParam("extension") String ext) {
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:201]: Image

Deleting an non-existing patient yields an ServerError. A DELETE should be idempotent

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 43]
```diff
@@ -112,326 +125,168 @@ public Response getEntryBySic(@PathParam("studyId") String id, @PathParam("sic")
...
-                pat = study.getPatientBySIC(sic);
-                if (pat != null) {
-                    throw OptInError.buildError(Status.CONFLICT, OptInErrorType.SIC_ALREADY_EXISTS, "Cannot create entry, SIC {0} already exists", sic);
-                }
-            }
+    @Path("{studyId}/patients/batch")
+    @PUT
+    @Consumes(MediaType.APPLICATION_JSON)
+    @Produces(MediaType.APPLICATION_JSON)
+    public Response createEntries(@PathParam("studyId") String id,
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:256]: Why do we have `saveEntry()` and here `createEntries()` ?

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 44]
```diff
@@ -112,326 +125,168 @@ public Response getEntryBySic(@PathParam("studyId") String id, @PathParam("sic")
...
-
-        PatientEntry oldEntry = study.getPatientByID(ref, root, ext);
-        if (oldEntry == null) {
-            throw OptInError.buildError(Status.NOT_FOUND, OptInErrorType.PATIENT_NOT_FOUND, "Patient not found");
-        }
-        PatientEntry newEntry = study.getPatientByID(ref, root, ext);
-        newEntry.setComment(entry.comment);
+    @Consumes(MediaType.APPLICATION_JSON)
+    @Produces(MediaType.APPLICATION_JSON)
+    public Response saveEntry(@PathParam("studyId") String id, @PathParam("reference") PatientReference ref,
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: Image

Malformed payload yields an ServerError instead of BAD REQUEST

**Review by akomii — CHANGES_REQUESTED** [review]
See comments attached, in summary:

- Empty collections should be returned as 200/`[ ]`
- Read operations implemented as POST
- Wrong PUT semantics
- Exceptions are not properly formatted

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 36 above)
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:124]: Because of the parameter extensions, that list might be a long one. When using url parameters like you would with GET requests, that url could exceed URL max character limit. A common solution for that problem is to use a POST request and send parameters as body.

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 34 above)
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:80]: changed it to a model `{detail: "PATIENT_NOT_FOUND"}`.

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 33 above)
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:100]: This is a valid error

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 36 above)
Comment (akomii) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:124]: Do you have an example for the payload? It seems like this method would actually be a search query. That is not clear from the url path and the method name

File: admin-gui/src/main/java/org/aktin/dwh/admin/JavaTimeMapperProvider.java
Comment (akomii) [reply admin-gui/src/main/java/org/aktin/dwh/admin/JavaTimeMapperProvider.java:1]: Still, please check if removing this class has an affect of the rest of the dwh

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 45]
```diff
@@ -103,108 +96,89 @@ public Response getPatientsOfStudy(@PathParam("id") String id) {
...
+     * @return updated entry
      */
     @Path("{studyId}/patients/{reference}/{extension}")
     @PUT
-    @Consumes({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
-    public Response saveEntry(@PathParam("studyId") String id, @PathParam("reference") PatientReference ref,
-                                @PathParam("extension") String ext, PatientEntryRequestDTO entry) {
+    @Consumes(MediaType.APPLICATION_JSON)
+    @Produces(MediaType.APPLICATION_JSON)
+    public Response updateEntry(@PathParam("studyId") String id, @PathParam("reference") PatientReference ref,
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: PUT does not work (no changes but comment)

Image

**Review by akomii — CHANGES_REQUESTED** [review]

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 36 above)
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:124]: `["4248733638","6790601213","3791899678","6451634779","7426931319","5977600398","8051844266","2381268180","7815303265","5647156122","5315103445","3694763933","9889845181","5745989379","5088635979","8763067297","6256782576","2708810975","5702679684","4609684415"]`

Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:124]: "It seems like this method would actually be a search query. That is not clear from the url path and the method name" Do you have any suggestions for the url? I renamed the method for clarity

Comment (akomii) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:124]: If you want to make it clean, it would be something like:

public Response searchEncounters(EncounterSearchRequest request)


POST /encounters/search

{
  "patientReferences": "patient",
  "extensions": ["424", "425", "426"]
}

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 46]
```diff
@@ -151,19 +152,19 @@ public Response getMasterData(@PathParam("reference") PatientReference ref,
...
      * @param entry: object that contains further information (participation, sic, comment) about the entry
      * @return updated entry
      */
     @Path("{studyId}/patients/{reference}/{extension}")
-    @PUT
+    @PATCH
     @Consumes(MediaType.APPLICATION_JSON)
     @Produces(MediaType.APPLICATION_JSON)
-    public Response updateEntry(@PathParam("studyId") String id, @PathParam("reference") PatientReference ref,
+    public Response partlyUpdateEntry(@PathParam("studyId") String id, @PathParam("reference") PatientReference ref,
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: partly is ambiguous. What are you exactly updating? How I understood, only the comments?

Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java]: I kept it ambiguous for possible later changes where comment isn't the only field being updated, but I will change the name

File: admin-gui/src/main/java/org/aktin/dwh/admin/JavaTimeMapperProvider.java
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/JavaTimeMapperProvider.java:1]: The rest of dwh seems to work without the class, but Instant is also used in other packages, and I saw Raphael's comment in ReportEntry.java: 
´´´
// TODO: Instant instead Date (fix problem: receiving nano and epochSecond when using Instant)
public Date created;
public Date data;
public Date start;
public Date end;
´´´

Comment (akomii) [reply admin-gui/src/main/java/org/aktin/dwh/admin/JavaTimeMapperProvider.java:1]: Classes/Depdencies should only be added if the affect the current scope. If the app works without JavaTimeMapperProvider, it should be removed

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 47]
```diff
@@ -1,218 +1,289 @@
...
+    /**
+     * Get all patient entries that belong to the study of the specified id.
+     *
+     * @param id
+     * @return Response with status 'ok' and the list of entries
+     */
+    @Path("{id}/patients")
+    @GET
+    @Produces(MediaType.APPLICATION_JSON)
+    public Response getPatientsOfStudy(@PathParam("id") String id) {
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:80]: nitpick: Should throw an error if study does not exist

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 48]
```diff
@@ -1,218 +1,289 @@
...
+        return Response.ok(patientEntry).build();
+    }
+
+    /**
+     * Get encounters for patients
+     *
+     * @param ref  patient reference
+     * @param extensions  extensions
+     * @return list of patient encounters
+     */
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:122]: nitpick: Dont forget to update docs too

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 36 above)
Comment (akomii) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:124]: I somehow cant find the patient via this method:

### Successful
Image

### Not successful
Image

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java [hunk 49]
```diff
@@ -119,51 +121,57 @@ public Response getPatient(@PathParam("studyId") String id,
...
      * @param entry: object that contains further information (participation, sic, comment) about the entry
      * @return updated entry
      */
     @Path("{studyId}/patients/{reference}/{extension}")
-    @PUT
+    @PATCH
     @Consumes(MediaType.APPLICATION_JSON)
     @Produces(MediaType.APPLICATION_JSON)
-    public Response updateEntry(@PathParam("studyId") String id, @PathParam("reference") PatientReference ref,
+    public Response updateEntryComment(@PathParam("studyId") String id, @PathParam("reference") PatientReference ref,
```
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:173]: Why such a big DTO if you only update the comment?

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java
Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:256]: Is this correct, that this is a PUT?

Comment (akomii) [inline admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:256]: What is wrong here? The log is not helpful at all

Image

Image

**Review by akomii — CHANGES_REQUESTED** [review]

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 49 above)
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:173]: Ultimately it is only necessary to write the audit log, I am going to open an issue in dwh-query regarding this

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 47 above)
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:80]: should be solved in dwh-query then?

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java
Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:256]: Improved logging by adding stacktrace

Comment (simhue) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:256]: No, I changed it to POST

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 47 above)
Comment (akomii) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:80]: No in this iteration at least

File: admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java (hunk 36 above)
Comment (akomii) [reply admin-gui/src/main/java/org/aktin/dwh/admin/optin/OptInEndpoint.java:124]: Still empty response:

Image

**Comment by akomii** [comment]
### Context

1. Given this patient (P1000):

Screenshot from 2026-03-02 14-29-02

2. We find him in the DWH as patient_num=3:

image

3. Accordingly, encounter_num=3:

image

4. Here we see the ide hashes:

image

5. The POST requests for encounter and masterdata:

image

image

### Problems
- `idEnc` is wrong (`pat_ide` is used)
- `zip` is `null` (should be 80636)
- `start_date` (Instant) is 1/17/2015, 16:03:00
- `end_date` (Instant) is 1/17/2015, 17:35:00
